kind: Simple
apiVersion: k3d.io/v1alpha4
name: my-cluster
image: rancher/k3s:v1.24.1-k3s1
servers: 3
agents: 3
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
# options:
#   k3s:
#     extraServerArgs:
#     - --no-deploy=traefik
